### ISSUE TITLE
About User Data

### ISSUE THREAD

**Issue by wogur0602** [swsnu/swpp17-team6#1]
### The way to save user data
1. Make new Model
2. Use User in django.contrib.auth.models + make addition user data support model(What I pushed today(1, Nov, 2017))

### The data type to save location
1. String(CharField)
2. Integer(IntegerField) => save location code
links about location code
https://github.com/google/open-location-code/blob/master/docs/olc_definition.adoc
https://en.wikipedia.org/wiki/Open_Location_Code
https://en.wikipedia.org/wiki/MapCode

**Comment by HS-YN** [comment]
1. In my opinion, it would be desirable to use model from HW3.
2. http://www.gadm.org/country 
This site has good database for location. Almost all datatypes are in string format, so CharField would come in handy.

**Comment by HS-YN** [comment]
Since the problem is already handled in sprint 2, I will mark this as closed.
