### ISSUE TITLE
TODO Frontend: F11. Ask Question

### ISSUE THREAD

**Issue by wogur0602** [swsnu/swpp17-team6#11]
1. Create Question Box in Main Component
1-1. Also, attach component of adding location and service tags
2. Finalize algorithm to decide to whom to send a given question (Difficult)

Exception Handling
1. Check empty string for content field of a question
2. No location tag or No service tag => Error

**Comment by seonghoon247** [comment]
"2. Finalize algorithm to decide to whom to send a given question" will be handled in sprint 4.  
We forgot to remove this part when reordering our user stories.   
Also it seems more appropriate to handle this issue in the backend.
