### ISSUE TITLE
TODO Frontend: F3. User can change settings of location for notification

### ISSUE THREAD

**Issue by wogur0602** [swsnu/swpp17-team6#13]
1. Create SettingsComponent (Similar to SignUpComponent)
  Difference with SignUpComponent
1-1. NotificationFrequencyComponent
1-2. BlockedServiceComponent

Exception Handling
1. No location tag or No service tag => Error

**Comment by timedilation** [comment]
Is there a reason to make another component instead of using SignUpComponent?

**Comment by seonghoon247** [comment]
I think functionality-wise, signup component and settings component are very similar.
However, in terms of the overall structure of the frontend, I think the signup and settings are rather independent components, and I think it would be better if the two are managed separately.

(This is just my personal opinion though. I am always open to other opinions!)
