### ISSUE TITLE
Problem with Changing Password in Settings

### ISSUE THREAD

**Issue by seonghoon247** [swsnu/swpp17-team6#16]
In user.service.ts, the update method sends the entire user object to the backend as below. 
```
    update(user: User): Promise<User>{
        var headers = new Headers({'Content-Type': 'application/json'});
        return this.http
            .get(this.tokenUrl).toPromise().then(()=> headers.append('X-CSRFToken', this.getCookie('csrftoken')))
            .then(() => this.http.put(this.userInfoUrl, JSON.stringify(user),
            {headers: headers}).toPromise().then(() => user));
            //.catch(this.handleError);
    }

```

However, when we initially get user info from the backend to change settings, the frontend does not receive the password, and the password is not saved into the user object.
```
def userinfo(request):
	if request.method == 'GET':
		# get userinfo - assume logged in
		if request.user is not None:
			userinfo = UserInfo.objects.get(id = request.user.id)
			result = {}
			result['email'] = request.user.username
			result['username'] = userinfo.nickname
			result['locations'] = getLocationStr(userinfo)
			result['services'] = getServiceStr(userinfo)
			return JsonResponse (result)
		else:
			return HttpResponse(status = 401)
```

Therefore, even if we save settings without changing password,  
the backend will still fetch the password form the **given instance (i.e. password = '')**  
and overwrite the existing password with the an empty string.

**Comment by seonghoon247** [comment]
I think there are two ways to solve this problem.

1. GET request of userinfo will also send the password to the frontend.
(But, I am afraid this is **NOT** the right way to do it regarding privacy and security.
Also, I think Django does not send the pure password, but instead, a modified/encrypted password)

2. Change the update method OR settings.componenet.ts to correctly process password

**Comment by timedilation** [comment]
In number 2, what did you mean by "correctly process password"?
I remember that many websites need users to type their password once again before changing settings, may be we could use that - then we also have to modify backend codes to test whether the password which user typed is correct.

**Comment by seonghoon247** [comment]
I think we could modify as below
1. modify the update method in user.service.ts to also send a flag that signals if there has been a password change or not.
2. modify the PUT request for userinfo in user/views.py so that it would receive password field only if the password flag is true.

Recap:
While the current implementation always receives password from frontend,
if there is no password change, there is no way for the frontend to send back the original password to the backend. (Even if we modify the GET request to also send the passoword, the backend would send an encrypted password, not the password itself)

```
elif request.method == 'PUT':
		# put userinfo - assume logged in
		if request.user is None:
			return HttpResponse(status = 401)
		user = request.user

		# TODO make it put
		req_data = json.loads(request.body.decode())
		password = req_data['password']
		locations = req_data['locations']
		services = req_data['services']
	
		user.set_password(password)
		userinfo = UserInfo.objects.get(id = user.id)
		services = servParse(services)
		setService(userinfo, services)
		locations = locParse(locations)
		try:
			setLocation(userinfo, locations)
		except UserInfo.DoesNotExist:
			return HttpResponse(status = 404)
		userinfo.save ()
		user.save()
		return HttpResponse(status = 204)

	else:
		return HttpResponseNotAllowed(['GET', 'PUT'])
```
