### ISSUE TITLE
Problem with Accessing Settings Page right after SignUp

### ISSUE THREAD

**Issue by seonghoon247** [swsnu/swpp17-team6#18]
After SignUp, if the user goes straight to the Settings page,  
the settings page will show all the fields (email, username, locations, services) as empty.

I wonder if this is just a simple error in the frontend,
OR
whether it actually has to do with the backend in terms of updating user information.

**Comment by HS-YN** [comment]
I think this problem occurs because of CSRF token issue. For signing up, user needs a csrf token, but the user needs another token when signing in. Rather than handling this issue, I resolved this bug by sending user to sign-in page rather than main page after signing up.
