### ISSUE TITLE
Block user to add same tag on service and blockedservice

### ISSUE THREAD

**Issue by timedilation** [swsnu/swpp17-team6#23]

**Comment by seonghoon247** [comment]
I think the functionality of blocking user from adding the same tag has already been implemented for services (and location). I think reusing this for blockedservice would save time and effort.

**Comment by timedilation** [comment]
[6cb61b18682ec62e89fb8ec43bf02d3ad9680850](url)

**Comment by HS-YN** [comment]
Reviewed, and didn't find any problem in this commit.
