### ISSUE TITLE
Problem with sending question

### ISSUE THREAD

**Issue by timedilation** [swsnu/swpp17-team6#26]
In frontend
`postQuestion(question: Question): Promise<number>`
works well. we tested it with console.log(question)

But in backend, question doesn't received.

**Comment by wogur0602** [comment]
Resolved in this Commit 0af54bb7f29c83eb762c86da0cffa89284fa4327 / 0f8cec330103057dd135f07e39d1dc627334d14d
You can also look up #14.

**Comment by HS-YN** [comment]
Since the commit was already reviewed, I will mark this issue as closed.
