### ISSUE TITLE
Problem: MyAnswersTab won't show the answers

### ISSUE THREAD

**Issue by seonghoon247** [swsnu/swpp17-team6#31]
MyAnswers Tab will currently not show the answers linked to a given question

**Comment by timedilation** [comment]
Solved
[https://github.com/swsnu/swpp17-team6/commit/5e7248416837ef9c29b42b6c0fa6687f0c5ac21b](url)

**Comment by HS-YN** [comment]
Reviewed [here](https://github.com/swsnu/swpp17-team6/commit/5e7248416837ef9c29b42b6c0fa6687f0c5ac21b).

Since my reviews are not directly related to this problem (refactoring/routing issue), so I will close this issue and handle it in my next commit.
