### ISSUE TITLE
Delay of redirecting users that are already signed in

### ISSUE THREAD

**Issue by HS-YN** [swsnu/swpp17-team6#32]
For signed in user,
1. Access `/signin`
2. Shows SigninComponent for a short amount of time
3. Since the user is signed in, then the user is redirected to `/main` right away.

This might not be a problem at this moment, but It **can be** severe problem if the service gets bigger.
Using `authguard` will resolve this issue, since it handles authority before initialization.

**Comment by seonghoon247** [comment]
Authentication Guard implemented in this commit 58b57b8f476963ba54f324ff04c0cbf3a9aa0fbe
