### ISSUE TITLE
auto-complete component not guarding invalid input

### ISSUE THREAD

**Issue by HS-YN** [swsnu/swpp17-team6#33]
1. Input invalid string on city (that does not exist in the list corresponding to province)
2. **Plask** the question
3. The question is successfully submitted to database, with invalid location information.
4. The question is successfully shown when refreshed, with no location information. 

I think it is not desirable to use this `auto-complete` html component, since it does not perfectly fit to our services, and it makes the system harder to maintain.

**Comment by HS-YN** [comment]
Including this issue, there are also some more problems that are propagated from `auto-complete`, including [this](https://github.com/swsnu/swpp17-team6/issues/29). Further problems on UX regarding this issue, for instance:

For tags(especially service) that does not exist,
1. Input some string
2. Result list `No Results found` covers `Add` button

This was somewhat bothersome for me.

**Comment by seonghoon247** [comment]
Also, after tackling with autocomplete for a while, it seems very difficult for the `auto-complete` to show the exact behavior that we intended. I also think using third-party features could be risky as we can not fully expect the behavior of it.  

I think it would be best to first change the existing 'auto-complete' for location tag(city) to a dropdown format, and modify later if we can implement 'autocomplete selection.' (i.e. what we really want to implement).

**Comment by seonghoon247** [comment]
However, with regarding the auto-complete functionality of the service tags,
which option do you think is better?

1. Let user type in and add service tags without any auto-complete with existing list of tags (ex. random list of tags, popular tags)
2. Keep the existing auto-complete functionality but implement it ourselves.  
(I think single auto-complete is quite doable)

P.S. For the 2nd option, we could follow the tutorial below.
[Tutorial: Creating an Angular2 Autocomplete](http://4dev.tech/2016/03/tutorial-creating-an-angular2-autocomplete/)

**Comment by HS-YN** [comment]
@seonghoon247 

I think option 2 is better than 1, considering UX. It might make our code complex, so it will be important to modularize the feature well.
Still option 1 has some good insight. At this moment, let's implement random list as recommendation, but change it with list of popular tags afterward. But currently, in frontend, service tag is not from backend, but from mock-backend. This should be handled first.
