### ISSUE TITLE
Problem when Refreshing the Page

### ISSUE THREAD

**Issue by seonghoon247** [swsnu/swpp17-team6#34]
When one refreshes a page (without necessarily doing any particular action),
the page would continuously refresh itself.

Pages that show the following misbehavior: (*Number of additional refreshes)
1. SignIn Page (1)*
2. SignUp Page (5+)
    * Also occurs when trying to access via Url when not logged in.
3. Main Page(5+)
    * Main Page -> try to access SignIn via Url ->(rerouted) Main Page (5+)
    * Main Page -> try to access SignUp via Url ->(rerouted) Main Page (5+)
    * Also occurs when trying to access via Url when logged in.
4. Settings Page (5+)

**Comment by seonghoon247** [comment]
Please let me know if the same error occurs or not!

**Comment by HS-YN** [comment]
Would you push the version that resolved this issue to Sprint3 branch?

**Comment by HS-YN** [comment]
My bad, I mistook this issue as redirecting problem. I will mark this issue `help wanted` again.
