### ISSUE TITLE
Restricted location API address

### ISSUE THREAD

**Issue by HS-YN** [swsnu/swpp17-team6#35]
First, ` ` and `%20` problem.
1. `api/locations/south korea` is not regarded as a valid API string.
2. So I temporarily changed this string to `api/locations/south%20korea`, but this will not resolve the fundamental issue.

Second, special characters problem.
1. In past submit, I modified regex of API address to contain ` - `.
2. But I found out that there are still other special characters, including ` ' `. This means that there are potentially more special characters to be added in location database.

Third, contaminated characters problem.
1. `china.CSV` or `japan.CSV` (which is not pushed into git due to this problem) contains some unique letters  outside of UTF-8 unicode. (for example, ă, ű)
2. They are contaminated when converted from microsoft access file to CSV file.
3. Thus, they are automatically converted into `?`.

**Comment by wogur0602** [comment]
Is it OK sending string data includes such characters as json request?
Also, ă, ű have the UTF-8 unicode(ă=C4 83, ű=C5 B1). [Converter](https://r12a.github.io/apps/conversion/)
If we can convert them as UTF-8 format, then we should send request as
GET ../api/location/level1
GET ../api/location/level2
GET ../api/location/level3
contains information of location name in json body.

**Comment by HS-YN** [comment]
@wogur0602 Then it may have nothing to do with unicode... Let me provide an example.

For instance, in canada, there is a city named St. François Xavier (canada(42)-manitoba(3)-1259)
But this is shown as St. Fran?ois Xavier.

**Comment by HS-YN** [comment]
Current API address : `..api/location/South%20Korea/seoul`
New API address : `..api/location/212/1`

**Comment by wogur0602** [comment]
Resolved in this commit bd00d29ed3244cce073d2e8ba981f7f43833ed7c
Please review the code. Thank you.
Also I fixed wiki
* [Design and Planning](https://github.com/swsnu/swpp17-team6/wiki/Design-and-Planning)
* [API url and HTTP Response](https://github.com/swsnu/swpp17-team6/wiki/API-url-and-HTTP-Response)

**Comment by HS-YN** [comment]
Reviewed. If there are no problem with this issue, anyone can close this issue.

**Comment by wogur0602** [comment]
We should handle .CSV problem

**Comment by wogur0602** [comment]
Resolved 11dcf9576b28790743b1d65263f7bbf39c6a3cf8
