### ISSUE TITLE
Discrepancy between User model and UserInfo model

### ISSUE THREAD

**Issue by HS-YN** [swsnu/swpp17-team6#36]
I found out that backend is using both User model and UserInfo model.
At this moment, they are paired well so that the problem is not propagated.
But using two models for user database may incur severe security issue and data discrepancy problem.

Recommended solution:
1. Make one usermodel called `User` that inherits default django user model
2. Change current interaction between User model and UserInfo model into methods of new User model.
3. Verify whether this change does not propagate error/bug/etc.

**Comment by wogur0602** [comment]
I think that the `UserInfo` model already handles two problems what you said.
1. Discrepancy: In [UserInfo model](https://github.com/swsnu/swpp17-team6/blob/Sprint3/PlaskBack/user/models.py#L31), there is a one-to-one field with User model, and they are initialized [at the same time](https://github.com/swsnu/swpp17-team6/blob/Sprint3/PlaskBack/user/views.py#L160).
2. Security: I think it is OK for security [checking authentication when GET or PUSH userinfo](https://github.com/swsnu/swpp17-team6/blob/Sprint3/PlaskBack/user/views.py#L227). Do you mean we should encrypt the contents of UserInfo model?

**Comment by wogur0602** [comment]
Link: [How to make custom User Model](https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html)

**Comment by HS-YN** [comment]
According to the link that you've provided, It is fine to use current user model without changing it. Most of all, since our primary goal is about our 'service'. As long as current user model don't make any problem in our scope of project, I think it is acceptable to maintain status quo.
