### ISSUE TITLE
Blocking inputs that are longer than backend capacity

### ISSUE THREAD

**Issue by HS-YN** [swsnu/swpp17-team6#38]
1. If the maximum length of specific data is 50 chars,
2. And the input is longer than 50 chars,
3. The input should be blocked.

**Comment by wogur0602** [comment]
Additional blocking input
1. Invalid email address as username
2. Invalid service tag character ! @ # $ % ^ & * ( ) " ' ; : < > . , / ? ~ `
3. Invaild username character  ! @ # $ % ^ & * ( ) " ' ; : < > . , / ? ~ `
4. Simple password

**Comment by HS-YN** [comment]
Resolved in #75

**Comment by HS-YN** [comment]
To describe detailed info,
1. Email validity check
2. ServiceTag, email length check

Didn't restrict service tag character or username character on purpose.
