### ISSUE TITLE
Accessing one answer input changes all answer inputs

### ISSUE THREAD

**Issue by HS-YN** [swsnu/swpp17-team6#40]
1. Open some questions, denoted by A and B, C, and so on.
2. write 'This is an answer' in the answer input textbox of A
3. Answer input textboxes of B, C and so on also shows 'This is an answer'

**Comment by seonghoon247** [comment]
It might not be directly related to this issue,
but I want to discuss how we should implement expand&collapse with regard to UX.

Would it be better to,
1. Allow users to expand as many questions as they want,
or
2. Allow users to only expand one question at a time.

**Comment by HS-YN** [comment]
@seonghoon247 That is also one of my concern!
At first, i thought that second option would be better, but consider this example:
1. There is question A, B, C with 30, 1, 5 answers each.
2. Question A is appended. (length = 3+30 = 33, roughly)
3. When appending question C, radical change of the length of list occurs. (length = 3+5 = 8)
This may be bothersome for users.

**Comment by seonghoon247** [comment]
We decided to go with the 2nd option.
Refreshing `answer=""` when a different tab is selected will solve the problem

**Comment by seonghoon247** [comment]
Resolved in this commit 6febb5af01277c5148e77abf8f6f496c58ce6374
