### ISSUE TITLE
[F7] Searching policy 

### ISSUE THREAD

**Issue by HS-YN** [swsnu/swpp17-team6#42]
It was actually discussed in #20 , but I think it is better to submit new issue and discuss the problem in here.

- [x] Defining regular expression for searching (already discussed in issue 20)
- [x] Defining weight for relevancy ( relevancy ~ serviceTag + blockedTag + location + string )
- [ ] Defining threshold for relevancy (i.e. only show questions that matches at least x%)

**Comment by wogur0602** [comment]
Policy Recommendation
1. Show _N_ questions in the descending _Search Point_ order.
2. Pointing Policy (_Search Point_ = _Location Point_ * _String and Tag Point_)
**(all types of variable are integer)**
 _Location Point_ = _L1 match_ ? 100 : 0 (when user select location tag only L1)
 _Location Point_ = _L1 match_ ? (_L2 match_ ? 100 : 20) : 0 (when user select location tag as L1 L2)
 _Location Point_ = _L1 match_ ? (_L2 match_ ? (_L3 match_ ? 100 : 25) : 5) : 0 (when user select all location tag)
 _String and Tag Point_ = _# of tag and word match to question_ * 100 / _total # of tag and word_

**Comment by seonghoon247** [comment]
I think it might be better if we add time factor in the Search Policy.

What about changing the first statement,
> Show N questions in the descending Search Point order.

as below?

"Show N questions in the descending Search Point order. 
In Search Point order, if two questions have the same search point, the one with more recent time stamp will go first. (i.e. has higher rank/priority.)

**Comment by HS-YN** [comment]
@wogur0602 That's great.
Since location weights that you've mentioned
```
Location Point = L1 match ? 100 : 0 (when user select location tag only L1)
Location Point = L1 match ? (L2 match ? 100 : 20) : 0 (when user select location tag as L1 L2)
Location Point = L1 match ? (L2 match ? (L3 match ? 100 : 25) : 5) : 0 (when user select all location tag)
```
are susceptible to policy change, these values should be like `final static int`, not magic number.

And how about **threshold**? should we set relevancy threshold to 70% or so?

**Comment by HS-YN** [comment]
@seonghoon247 Do you mean that the user cannot select the sorting order?
Quite a few services that provides DB searching give users some options like `sort alphabetically`, `sort by time`, `sort by relevancy`, etc.

**Comment by wogur0602** [comment]
Oh. I forgot the time... I think we should discuss that after today's practice session

**Comment by timedilation** [comment]
@HS-YN @seonghoon247 As we decide that the key feature of the app is simplicity, I think it will be better to not allow user to change sorting order. However user might need sorting based on time and relevancy, so what about adding only these two sorting options?

**Comment by HS-YN** [comment]
Our conclusion last time was:
1. Not allow tag-based search (if required, by pressing the tag in any question, user can see the questions with given tag in a time order)
2. Filter out location -> Filter out strings (threshold: 50, but susceptible to change) -> Sort by time

About sorting, there might be two options:
* Make function that appropriately reflects time and relevancy, and do not give sorting option
* Give two sorting option as mentioned above.

**Comment by wogur0602** [comment]
@HS-YN 
Should we insert time as searching behavior?
I think there's some problem on "Sort by time". Relevance is more important than time diff when search with some keyword.
