### ISSUE TITLE
[F7] Getter method for searching questions

### ISSUE THREAD

**Issue by HS-YN** [swsnu/swpp17-team6#43]
Should be in accordance with #42 .

Some points of implementation
 - **search** step-by-step (i.e. get 90% accordance, get 80% accordance, get 70% accordance... / get today's question, get yesterday's question...) versus **search** once (i.e. get 50% accordance and sort by accordance / get questions for 1 week and sort by latest update)
 - **search** question only versus **search** both question and answer

**Comment by wogur0602** [comment]
I'm working on [this branch](https://github.com/swsnu/swpp17-team6/tree/search_question_sprint4).
@timedilation 
If the policy is finalized as inserting time-sort, [the code](https://github.com/swsnu/swpp17-team6/blob/search_question_sprint4/PlaskBack/ask/views.py#L181) should be changed.

**Comment by wogur0602** [comment]
[Fix HTTP request as](https://github.com/swsnu/swpp17-team6/wiki/API-url-and-HTTP-Response) because of error when send GET request with request body. (We should send info of GET request with url)
* [DjangoDocument](https://docs.djangoproject.com/en/1.11/ref/request-response/)

**Comment by wogur0602** [comment]
I found the way to send info without url by using POST method: b55b0477c0cfcdc163cf781621e2de009e4a5f78

I will fix out the code and the document

**Comment by timedilation** [comment]
Ok! I've just checked the document and codes.

**Comment by wogur0602** [comment]
This feature needs refactoring. #52

**Comment by wogur0602** [comment]
Refactored with using from GET to POST method on e4f15a30b74fcc995880965c866693a2426ee795
Therefore the [HTTP request / response](https://github.com/swsnu/swpp17-team6/wiki/API-url-and-HTTP-Response) is modified
