### ISSUE TITLE
[F6] Send notification

### ISSUE THREAD

**Issue by HS-YN** [swsnu/swpp17-team6#44]
1. Backend refreshes data regularly.
1-1. Find if there are questions relevant to user (based on notification_frequency)
1-2. Find if there are answers for the question posted by user (regardless of notification_frequency)
2. Backend sends notification request to frontend if required.
3. Frontend sends notification using chrome extension.
3-1. "While you're away, n questions arrived for you including (latest recommendation). Why don't you answer them?"
3-2. "You've got the answer for the question (user's question). Check it out!"

- [x] Backend data refresh
- [ ] Backend-to-frontend communication
- [ ] Frontend notification using chrome extension

**Comment by seonghoon247** [comment]
I've been tackling this problem for a while, and I think we need to finalize how to implement.

**1. (Remote) Push Notification**
Method: Connect backend server with a third-party push service. (ex. Firebase, Google Cloud Messaging)
Effect: Users can receive notifications even if they are not using our service.
Difficulty: We need to connect both the frontend and the backend to the push service.

**2. (In-app) Notification from the backend**
Method: Create a web socket (channel) between frontend and backend.
Effect: Users can receive notifications while they are using our service.
Difficulty: We need to establish a web socket.

**3. (In-app) Notification from the frontend**
Method: Frontend periodically receives data from backend and notify if there is any change.
Effect: Users can receive notifications while they are in the main page.
Difficulty: (Least Difficult of the three)
Side Effect: Can create a lot of stress to the database.

**Comment by wogur0602** [comment]
I think 2. is better than the others. If we choose 2., we can handle the noti problem in range of python Django / typescript Angular with better performance.

**Comment by timedilation** [comment]
2.. will be best.. If we could manage web socket. Let's try!

**Comment by seonghoon247** [comment]
Notification implemented using websocket.

Resolved in these commits:  
7a84cbef656aeaefc2cb7cc069f35e04c9f791f6
1dd9121e27036feff62065c8b58b2a674b87abfc
