### ISSUE TITLE
[F9] Notification policy

### ISSUE THREAD

**Issue by HS-YN** [swsnu/swpp17-team6#45]
1. Notification when the answer for question has arrived
1-1. **How many?** : only when the first answer was posted vs. whenever the answer was posted
1-2. **How long?** : send notification regardless of duration (ex. send notification of answer(11/27) for question(11/10)) vs. send notification for only certain period of time (ex. only notify for 1 day)
1-3. **When?** : right away (i.e. continuous refreshment of backend) vs. regularly (i.e. every n min.)

2. Notification when there are recommended questions
2-1. **Frequency?** : freely select frequency (ex. for every 37 minutes) vs. select under given frequency (ex. select one of the 5/10/30/60/120)
2-2. **How long?** : send notification regardless of duration (ex. send notification for question(11/10) in 11/27) vs. send notification for only certain period of time (ex. only notify questions uploaded in 1 day)
2-3. **Ignore?** : can ignore question after seeing once vs. questions that are not answered always counted as the target of notification

**Comment by seonghoon247** [comment]
Notification has been implemented for 1, but not 2.

1. Regarding Notification for receiving answers,
1-1. Notifications will be sent until the questioner selects an answer.
1-2. Regardless of duration, until the questioner selects an answer.
1-3. Right away.

Resolved in these commits
7a84cbef656aeaefc2cb7cc069f35e04c9f791f6
1dd9121e27036feff62065c8b58b2a674b87abfc
