### ISSUE TITLE
[F10] Random tag recommendation for settings/signup

### ISSUE THREAD

**Issue by HS-YN** [swsnu/swpp17-team6#49]
Our current frontend service is using mock service database, so our first job is to:
- [x] Implement frontend service tag
- [x] Implement backend service tag

Then, some functionalities should be implemented:
- [x] Implement random tag recommendation

If possible, some useful functionalities can be implemented:
( Please visit #50 )

**Comment by wogur0602** [comment]
Resolved in backend on commit dd5bc08b7fc0d4e5f09014c04f5edb520ed14d88

**Comment by wogur0602** [comment]
Modified [document](https://github.com/swsnu/swpp17-team6/wiki/API-url-and-HTTP-Response) for this feature.

**Comment by HS-YN** [comment]
Implemented in #74

**Comment by wogur0602** [comment]
Confirmed, I will close the issue
