### ISSUE TITLE
[F13] Ordering question and answer

### ISSUE THREAD

**Issue by HS-YN** [swsnu/swpp17-team6#51]
At the moment, backend sends question and answer in somewhat unordered manner.

Backend should reorder selected questions in some order (posted time / unique id / recent updated time i.e. answer time), as well as answers.

- [x] Ordering questions
- [x] Ordering answers

**Comment by wogur0602** [comment]
Resolved backend on this commit b6f93f17b4468d0feb721d026b5f776d1b895307
But there's some problem on frontend when refreshing the page(the order changes with random order)

**Comment by HS-YN** [comment]
There are still some minor rendering problem, but since it is not possible to handle it with frontend or backend, I will close this issue.
