### ISSUE TITLE
[SP4] Code refactoring

### ISSUE THREAD

**Issue by HS-YN** [swsnu/swpp17-team6#52]
- [x] Backend - ask
- [x] Backend - location
- [x] Backend - user
- [x] Frontend - models (answer, question, user)
- [x] Frontend - Signin / Signup
- [x] Frontend - Main (maintab, question, answer)
- [x] Frontend - routing

1. Refactor code
2. Verify whether the testing is in accordance with the new code
3. Link the commit in this issue

**Comment by wogur0602** [comment]
I did backend refactoring: on this commit e4f15a30b74fcc995880965c866693a2426ee795.

**Comment by wogur0602** [comment]
more backend refactoring on b7c2dba20831e8acaddf06c08fad8445844c9e52
