### ISSUE TITLE
[F15] Choosing best answer for question

### ISSUE THREAD

**Issue by HS-YN** [swsnu/swpp17-team6#53]
- [x] Make one-to-one table of question and its selected answer
- [x] Implement backend functionalities
- [x] Implement frontend interface for selection / marks for selected question.

**Comment by timedilation** [comment]
Done at #88

**Comment by timedilation** [comment]
Minor enhancement left
1. Mark chosen answer different with others
2. update immediately when someone choose answer (answer button still appears before refreshing it)
3. Mark closed question different with others
